### ISSUE TITLE
Issue with the downloaded runc version

### ISSUE THREAD

**Issue by Noufel17** [kubespray-offline/kubespray-offline#45]
The offline provisioning fails because it doesn't find any runc download in the files server I think,
the error is copied bellow, the error is in download item task and I think it is an empty mirrors list:, I also checked the files downloaded 
and I found that the version downloaded is not the one kubespray is trying to find : I ran a curl from one of the nodes and the file was downloaded to it normally: curl -LO http://10.100.0.35/files/runc/v1.1.9/runc.amd64, and I printed the url got by the task which was http://10.100.0.35/files/runc/v1.1.10/runc.amd64, constructed by this string runc_download_url: "{{ files_repo }}/runc/{{ runc_version }}/runc.{{ image_arch }}", the issue is a mismatch between the two in the runc_version, where do I find this runc_version variable in the kubespray files, I ran my downloades using the same kubespray version and source (kubespraynew directory) so I don't know why was this missmatch, I need some help to figure it out.

TASK [container-engine/runc : Download_file | Download item] *************************************************************
task path: /home/noufel/kubespray_offline/k8s_provisionner/kubespraynew/roles/download/tasks/download_file.yml:93
The full traceback is:
Traceback (most recent call last):
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 529, in _execute
    self._task.post_validate(templar=templar)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/playbook/task.py", line 290, in post_validate
    super(Task, self).post_validate(templar)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/playbook/base.py", line 543, in post_validate
    value = method(attribute, getattr(self, name), templar)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/playbook/task.py", line 298, in _post_validate_args
    args = templar.template(value)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 797, in template
    d[k] = self.template(
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 771, in template
    result = self.do_template(
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 1015, in do_template
    res = myenv.concat(rf)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/native_helpers.py", line 43, in ansible_eval_concat
    head = list(islice(nodes, 2))
  File "<template>", line 18, in root
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 295, in wrapper
    ret = func(*args, **kwargs)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/plugins/filter/core.py", line 251, in rand
    return r.choice(end)
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
fatal: [master1]: FAILED! => {
    "changed": false
}
The full traceback is:
Traceback (most recent call last):
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 529, in _execute
    self._task.post_validate(templar=templar)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/playbook/task.py", line 290, in post_validate
    super(Task, self).post_validate(templar)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/playbook/base.py", line 543, in post_validate
    value = method(attribute, getattr(self, name), templar)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/playbook/task.py", line 298, in _post_validate_args
    args = templar.template(value)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 797, in template
    d[k] = self.template(
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 771, in template
    result = self.do_template(
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 1015, in do_template
    res = myenv.concat(rf)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/native_helpers.py", line 43, in ansible_eval_concat
    head = list(islice(nodes, 2))
  File "<template>", line 18, in root
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 295, in wrapper
    ret = func(*args, **kwargs)
  File "/home/noufel/.local/lib/python3.10/site-packages/ansible/plugins/filter/core.py", line 251, in rand
    return r.choice(end)
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
fatal: [master2]: FAILED! => {
    "changed": false
}

**Comment by Noufel17** [comment]
Also this is the list of working mirrors: It is empty because the URL that kubespray is trying to find was not found (with runc version 1.1.10)
TASK [container-engine/runc : Download_file | Get the list of working mirrors] *******************************************
task path: /home/noufel/kubespray_offline/k8s_provisionner/kubespraynew/roles/download/tasks/download_file.yml:86
ok: [master1] => {
    "ansible_facts": {
        "valid_mirror_urls": []
    },
    "changed": false
}
ok: [master2] => {
    "ansible_facts": {
        "valid_mirror_urls": []
    },
    "changed": false
}

**Comment by tmurakam** [comment]
Which version of kubespray-offline are you using?
The latest version (v2.26.0-0) should download runc version 1.1.13.

**Comment by Noufel17** [comment]
I'm using v2.23.1 because I think it is compatible with my Kubespray version (2.23.2), I can't change the Kubespray version I use, I checked the generated files list, and it contains: https://github.com/opencontainers/runc/releases/download/v1.1.9/runc.amd64,
I just replaced docker with nerdctl to avoid the depricated images issue

**Comment by tmurakam** [comment]
The runc version is defined in `roles/download/defaults/main/main.yml` of kubespray 2.23.2. The version is v1.1.9.

**Comment by Noufel17** [comment]
okey then I must have used the wrong version of Kubespray, because roles/download/defaults/ doesn't exists in my kubespray source, I think it was removed in Kubespray 2.24, can you tell me where can I find the versions variables in the newer versions?

**Comment by Noufel17** [comment]
I found it, kubespray-defaults/defaults/main/download.yml

**Comment by Noufel17** [comment]
Issue fixed, Just a missmatch in version, I actually was using Kubespray 2.24.0, which uses runc 1.1.10, thank you for your time @tmurakam
